swagger: "2.0"
info:
 title: "Rentokil Portals API"
 description: "Portals API implement PNOL services while consuming and returning JSON"
 version: "1.0.0"
host: "portals-api-dev.appspot.com"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
- "text/html"
- "text/css"
- "application/javascript"
- "image/svg+xml"
schemes:
- "https"
paths:
 "/api/getPestSpecies":
   get:
     description: "Get a JSON object with the pest species"
     operationId: "getPestSpecies"
     parameters:
       - name: pest_group_id
         in: query
         description: Get a JSON object with the pest species
         required: true
         type: string
     produces:
     - "application/json"
     responses:
       200:
         description: "Successfully got the Pest Species JSON object"
 "/docs":
   get:
      description: "Returns index.html file"
      operationId: "getIndex"
      security: []
      produces:
        - "text/html"
      responses:
        302:
          description: "redirect"
        304:
          description: "index.html"
        200:
          description: "index.html"
 "/docs/openapi.yaml":
   get:
      description: "Returns index.html file"
      operationId: "getYaml"
      security: []
      produces:
        - "text/yaml"
      responses:
        302:
          description: "redirect"
        304:
          description: "openapi.yaml"
        200:
          description: "openapi.yaml"